---
apiVersion: v1
kind: Secret
metadata:
  name: wp-db-secret-{{ id }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-{{ id }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-{{ id }}
  labels:
    app: mysql-{{ id }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-{{ id }}
  template:
    metadata:
      labels:
        app: mysql-{{ id }}
    spec:
      containers:
        - name: database-{{ id }}
          image: mysql:5.7
          args:
            - "--ignore-db-dir=lost+found"
          envFrom:
            - secretRef:
                name: wp-db-secret-{{ id }}
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data-{{ id }}
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_DATABASE
              value: mysql
            - name: MYSQL_PASSWORD
              value: ${MYSQL_DB_PASSWORD}
            - name: MYSQL_USER
              value: mysql  
      volumes:
        - name: mysql-data-{{ id }}
          persistentVolumeClaim:
            claimName: mysql-volume-{{ id }}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service-{{ id }}
spec:
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: mysql-{{ id }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-volume-{{ id }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-{{ id }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-{{ id }}
  template:
    metadata:
      labels:
        app: wordpress-{{ id }}
    spec:
      containers:
        - name: wordpress-{{ id }}
          image: wordpress:5.8.3-php7.4-apache
          ports:
            - containerPort: 80
              name: wordpress-{{ id }}
          volumeMounts:
            - name: wordpress-data-{{ id }}
              mountPath: /var/www
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service-{{ id }}.default.svc.cluster.local
            - name: WORDPRESS_DB_NAME
              value: mysql
            - name: WORDPRESS_DB_USER
              value: mysql
            - name: WORDPRESS_DB_PASSWORD
              value: ${MYSQL_DB_PASSWORD}
      volumes:
        - name: wordpress-data-{{ id }}
          persistentVolumeClaim:
            claimName: wordpress-volume-{{ id }}
---
kind: Service
apiVersion: v1
metadata:
  name: wordpress-service-{{ id }}
spec:
  selector:
    app: wordpress-{{ id }}
  ports:
    - name: http
      protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wp-mysql-ingress-{{ id }}
spec:
  rules:
    - host: {{ id }}.localhost
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: wordpress-service-{{ id }}
                port:
                  number: 80
